import * as Handlebars from 'handlebars';
import fs = require('fs');
import path = require('path');
import tl = require("azure-pipelines-task-lib/task");

export function registerHelpers(): void {
    // GroupBy helper
    Handlebars.registerHelper('groupBy', function(items: any[], field: string, options: any) {
        if (!Array.isArray(items) || !field) return '';
        const groups: Record<string, any[]> = {};
        items.forEach(item => {
            if (!item || typeof item !== 'object') return;
            const key = item[field] || 'Other';
            if (!groups[key]) groups[key] = [];
            groups[key].push(item);
        });
        let result = '';
        Object.keys(groups).forEach(key => {
            result += options.fn({ key, items: groups[key] });
        });
        return result;
    });
}

export function GenerateMarkdownReleaseNotes(
    data: any,
    outputFile: string,
    templateFile?: string
){

    // Get template
    let template: string;
    try {
        const hasValidTemplateFile = templateFile && 
            templateFile.trim() !== '' && 
            fs.existsSync(templateFile) && 
            fs.statSync(templateFile).isFile();
            
        if (hasValidTemplateFile) {
            template = fs.readFileSync(templateFile, 'utf8');
            console.log(`Using custom template: ${templateFile}`);
        } else {
            template = fs.readFileSync(
                path.join(__dirname, '..', '..', 'defaultTemplateMarkdown.hbs'),
                'utf-8'
            );
            console.log('Using default template');
        }
    } catch (error) {
        console.warn(`Error reading template file: ${error}. Using default template.`);
        template = fs.readFileSync(
            path.join(__dirname, '..', '..', 'defaultTemplateMarkdown.hbs'),
            'utf-8'
        );
    }


    template += `
    ---
    
    _Generated by [IeuanWalker.ReleaseNotesGenerator](https://marketplace.visualstudio.com/items?itemName=IeuanWalker.ReleaseNotesGenerator)_`


    // Generate release notes
    let releaseNotes: string;
    try {
        require('handlebars-helpers')({ Handlebars });
        const templateMarkdownFunc = Handlebars.compile(template);
        releaseNotes = templateMarkdownFunc(data);
    } catch (error) {
        tl.setResult(tl.TaskResult.Failed, `Failed to generate release notes from template: ${error}`);
        return;
    }    

    // Save release notes to file
    try {
        const outputDir = path.dirname(outputFile);
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }
        fs.writeFileSync(outputFile, releaseNotes, 'utf8');
        console.log(`Release notes written to: ${outputFile}`);
    } catch (error) {
        tl.setResult(tl.TaskResult.Failed, `Failed to write release notes to file: ${error}`);
        return;
    }

    tl.setResult(tl.TaskResult.Succeeded, `Markdown release notes generated successfully`);    
}

export function GenerateHtmlReleaseNotes(
    data: any,
    outputFile: string,
    templateFile?: string
){

    // Get template
    let template: string;
    try {
        const hasValidTemplateFile = templateFile && 
            templateFile.trim() !== '' && 
            fs.existsSync(templateFile) && 
            fs.statSync(templateFile).isFile();
            
        if (hasValidTemplateFile) {
            template = fs.readFileSync(templateFile, 'utf8');
            console.log(`Using custom template: ${templateFile}`);
        } else {
            template = fs.readFileSync(
                path.join(__dirname, '..', '..', 'defaultTemplateHtml.hbs'),
                'utf-8'
            );
            console.log('Using default template');
        }
    } catch (error) {
        console.warn(`Error reading template file: ${error}. Using default template.`);
        template = fs.readFileSync(
            path.join(__dirname, '..', '..', 'defaultTemplateHtml.hbs'),
            'utf-8'
        );
    }

    const footerHtml = `
    <footer>
        <p>
            Generated by <a href="https://marketplace.visualstudio.com/items?itemName=IeuanWalker.ReleaseNotesGenerator">IeuanWalker.ReleaseNotesGenerator</a>
        </p>
    </footer>
    `;
    if (template.includes('</body>')) {
        template = template.replace('</body>', `${footerHtml}\n</body>`);
    } else {
        template += footerHtml;
    }

    // Generate release notes
    let releaseNotes: string;
    try {
        require('handlebars-helpers')({ Handlebars });
        const templateMarkdownFunc = Handlebars.compile(template);
        releaseNotes = templateMarkdownFunc(data);
    } catch (error) {
        tl.setResult(tl.TaskResult.Failed, `Failed to generate release notes from template: ${error}`);
        return;
    }    

    // Save release notes to file
    try {
        const outputDir = path.dirname(outputFile);
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }
        fs.writeFileSync(outputFile, releaseNotes, 'utf8');
        console.log(`Release notes written to: ${outputFile}`);
    } catch (error) {
        tl.setResult(tl.TaskResult.Failed, `Failed to write release notes to file: ${error}`);
        return;
    }

    tl.setResult(tl.TaskResult.Succeeded, `Markdown release notes generated successfully`);    
}