name: Build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-vsix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefix CommitRangeReleaseNotesTask

      - name: Install tfx-cli
        run: npm install -g tfx-cli

      - name: Package Azure DevOps Extension
        run: tfx extension create --manifest-globs vss-extension.json

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: '*.vsix'
